name: Test R with renv

on:
  push:
    branches:
      - main  # Se ejecuta cuando subes cambios a la rama principal
  pull_request:
    branches:
      - main  # Se ejecuta en cada Pull Request

jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'  # versión de R que queramos usar

      - name: Configurar renv
        uses: r-lib/actions/setup-renv@v2

      - name: Ejecutar script de prueba
        run: Rscript Script.R 
